#!/usr/bin/env python3
"""Write preview/textures.js: downscaled copies of assets/textures/*.png as
data URIs, so the browser preview renders with the real texture pack.
Run after tools/make_textures.py."""
import base64
import io
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "textures")
OUT = os.path.join(ROOT, "preview", "textures.js")

# key -> (file, flipbook grid, preview size)
PACK = {
    "Smoke": ("Smoke_8x8.png", 8, 768),
    "Fire": ("Fire_8x8.png", 8, 768),
    "InkWisp": ("InkWisp_4x4.png", 4, 512),
    "Spark": ("Spark_4x4.png", 4, 512),
    "Ember": ("Ember_4x4.png", 4, 256),
    "Shard": ("Shard_4x4.png", 4, 256),
    "Flare": ("Flare.png", 1, 256),
    "Ring": ("Ring.png", 1, 512),
    "Crack": ("Crack.png", 1, 768),
    "Rune": ("Rune.png", 1, 768),
    "Glyph": ("Glyph.png", 1, 128),
    "Crescent": ("Crescent.png", 1, 512),
    "Snow": ("Snow.png", 1, 64),
}

lines = ["// Generated by tools/embed_preview_textures.py - do not edit.", "window.GRIMOIRE_TEX = {"]
total = 0
for key, (name, grid, size) in PACK.items():
    im = Image.open(os.path.join(SRC, name)).convert("RGBA")
    w, h = im.size
    scale = size / max(w, h)
    im = im.resize((max(1, int(w * scale)), max(1, int(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    data = base64.b64encode(buf.getvalue()).decode()
    total += len(data)
    lines.append(f'  {key}: {{ grid: {grid}, src: "data:image/png;base64,{data}" }},')
lines.append("};")
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {os.path.relpath(OUT, ROOT)} ({total // 1024} KB of image data)")
