#!/usr/bin/env python3
"""Generate dist/InstallGrimoireVFX.lua: a single script you paste into the
Roblox Studio command bar to recreate every VFX script in any place.

Usage (from the repo root):  python3 tools/make_installer.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dist", "InstallGrimoireVFX.lua")

# (source path, Roblox service, path inside the service)
TARGETS = [
    ("src/ReplicatedStorage/VFX", "ReplicatedStorage", []),
    ("src/ServerScriptService/SpellService.lua", "ServerScriptService", []),
    ("src/ServerScriptService/SpellServer.server.lua", "ServerScriptService", []),
    ("src/StarterPlayer/StarterPlayerScripts/SpellClient.client.lua", "StarterPlayer", ["StarterPlayerScripts"]),
    ("src/StarterPlayer/StarterPlayerScripts/VFXTestBinds.client.lua", "StarterPlayer", ["StarterPlayerScripts"]),
]


def long_string(text):
    level = 0
    while ("]" + "=" * level + "]") in text:
        level += 1
    eq = "=" * level
    # A newline right after the opening bracket is dropped by Lua, so add one.
    return "[" + eq + "[\n" + text + "]" + eq + "]"


def script_info(filename):
    if filename.endswith(".server.lua"):
        return "Script", filename[: -len(".server.lua")]
    if filename.endswith(".client.lua"):
        return "LocalScript", filename[: -len(".client.lua")]
    return "ModuleScript", filename[: -len(".lua")]


def emit(path, parent_var, lines, counter):
    full = os.path.join(ROOT, path)
    counter[0] += 1
    var = f"i{counter[0]}"
    if os.path.isdir(full):
        name = os.path.basename(full)
        lines.append(f'local {var} = make("Folder", "{name}", {parent_var})')
        for child in sorted(os.listdir(full)):
            emit(os.path.join(path, child), var, lines, counter)
    elif full.endswith(".lua"):
        cls, name = script_info(os.path.basename(full))
        with open(full, encoding="utf-8") as f:
            source = f.read()
        lines.append(f'make("{cls}", "{name}", {parent_var}, {long_string(source)})')


def main():
    lines = [
        "--[[",
        "\tLife of Grimoire VFX installer (generated by tools/make_installer.py)",
        "",
        "\tHOW TO USE: open your game in Roblox Studio, open View > Command Bar,",
        "\tpaste this WHOLE file into the command bar and press Enter.",
        "",
        "\tIt creates:",
        "\t  ReplicatedStorage.VFX                         (Config, Util, Spells, VFXController)",
        "\t  ServerScriptService.SpellService              (ModuleScript, spell API + boss casts)",
        "\t  ServerScriptService.SpellServer               (Script)",
        "\t  StarterPlayer.StarterPlayerScripts.SpellClient   (LocalScript)",
        "\t  StarterPlayer.StarterPlayerScripts.VFXTestBinds  (LocalScript, debug keys 1-8)",
        "",
        "\tIt refuses to run if any of those already exist, so it never",
        "\toverwrites your own scripts. Delete or rename them first to reinstall.",
        "]]",
        "",
        "local function make(className, name, parent, source)",
        "\tlocal inst = Instance.new(className)",
        "\tinst.Name = name",
        "\tif source then",
        "\t\tinst.Source = source",
        "\tend",
        "\tinst.Parent = parent",
        "\treturn inst",
        "end",
        "",
        'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
        'local ServerScriptService = game:GetService("ServerScriptService")',
        'local StarterPlayerScripts = game:GetService("StarterPlayer"):WaitForChild("StarterPlayerScripts")',
        "",
        "local conflicts = {}",
        'if ReplicatedStorage:FindFirstChild("VFX") then',
        '\ttable.insert(conflicts, "ReplicatedStorage.VFX")',
        'end',
        'if ServerScriptService:FindFirstChild("SpellService") then',
        '\ttable.insert(conflicts, "ServerScriptService.SpellService")',
        'end',
        'if ServerScriptService:FindFirstChild("SpellServer") then',
        '\ttable.insert(conflicts, "ServerScriptService.SpellServer")',
        'end',
        'if StarterPlayerScripts:FindFirstChild("SpellClient") then',
        '\ttable.insert(conflicts, "StarterPlayerScripts.SpellClient")',
        'end',
        'if StarterPlayerScripts:FindFirstChild("VFXTestBinds") then',
        '\ttable.insert(conflicts, "StarterPlayerScripts.VFXTestBinds")',
        'end',
        "if #conflicts > 0 then",
        '\twarn("[GrimoireVFX] Not installed. These already exist (delete or rename them first): " .. table.concat(conflicts, ", "))',
        "\treturn",
        "end",
        "",
    ]
    counter = [0]
    parents = {
        "ReplicatedStorage": "ReplicatedStorage",
        "ServerScriptService": "ServerScriptService",
        "StarterPlayer": "StarterPlayerScripts",
    }
    for path, service, _ in TARGETS:
        emit(path, parents[service], lines, counter)
    lines += [
        "",
        'print("[GrimoireVFX] Installed. Press Play and use keys 1-8 (set Config.DEBUG = false to hide the test binds).")',
        "",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT) // 1024} KB, {counter[0]} instances)")


if __name__ == "__main__":
    main()
